# https://www.thinktecture.com/en/kubernetes/ssl-certificates-with-cert-manager-in-kubernetes/
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Staging API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: guilhermeihara@gmail.com
    privateKeySecretRef:
      name: account-key-prod
    solvers:
    - http01:
       ingress:
         class: nginx